# Generated by Django 6.0.6 on 2026-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="utr_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="upi_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("pending_verification", "Pending Verification"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="pending_payment",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
