# Generated by Django 6.0.6 on 2026-06-07 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventapp",
            "0002_booking_updated_at_booking_utr_number_payment_upi_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="event",
            name="rows",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="event",
            name="seats_per_row",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.CharField(max_length=5)),
                ("number", models.PositiveIntegerField()),
                ("seat_label", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("blocked", "Blocked"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="eventapp.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "row", "number")},
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(
                blank=True, related_name="bookings", to="eventapp.seat"
            ),
        ),
    ]
